#ifndef _FASP_DS_ERROR_H_
#define _FASP_DS_ERROR_H_



/*
 * Protocol errors.
 */
#define FASP_ERR_PROTO_BASE          (-1000)
#define FASP_ERR_VERSION_MISMATCH    (FASP_ERR_PROTO_BASE -1)
#define FASP_ERR_INVALID_TYPE        (FASP_ERR_PROTO_BASE -2)
#define FASP_ERR_MSG_TOO_BIG         (FASP_ERR_PROTO_BASE -3)
#define FASP_ERR_MSG_TOO_SMALL       (FASP_ERR_PROTO_BASE -4)
#define FASP_ERR_PROTO_END           (FASP_ERR_PROTO_BASE -4)
#define FASP_ERR_PROTO_NUM           (FASP_ERR_PROTO_BASE - FASP_ERR_PROTO_END)


/*
 * Local errors.
 */
/* FIXME: eliminate these error codes; fold into <fasp/fasp_errno.h> */

#define FASP_ERR_LOCAL_BASE          (-2000)
#define FASP_ERR_NOMEM               (FASP_ERR_LOCAL_BASE - 1)
#define FASP_ERR_SYS_NORESOURCE      (FASP_ERR_LOCAL_BASE - 2)
#define FASP_ERR_FILENAME_TOO_BIG    (FASP_ERR_LOCAL_BASE - 3)
#define FASP_ERR_DIR_OPEN_FAILED     (FASP_ERR_LOCAL_BASE - 4)
#define FASP_ERR_FILE_OPEN_FAILED    (FASP_ERR_LOCAL_BASE - 5)
#define FASP_ERR_FILE_STAT_FAILED    (FASP_ERR_LOCAL_BASE - 6)
#define FASP_ERR_FILE_EACCES         (FASP_ERR_LOCAL_BASE - 7)
#define FASP_ERR_FILE_EEXIST         (FASP_ERR_LOCAL_BASE - 8)
#define FASP_ERR_FILE_OTHER          (FASP_ERR_LOCAL_BASE - 9)
#define FASP_ERR_FILE_NOT_REGULAR    (FASP_ERR_LOCAL_BASE - 10)
#define FASP_ERR_INVALID_OBJECT_TYPE (FASP_ERR_LOCAL_BASE - 11)
#define FASP_ERR_READLINK_FAILED     (FASP_ERR_LOCAL_BASE - 12)
#define FASP_ERR_FILE_LSTAT_FAILED   (FASP_ERR_LOCAL_BASE - 13)
#define FASP_ERR_FILE_SYMLINK_NOT    (FASP_ERR_LOCAL_BASE - 14)
#define FASP_ERR_FILE_CREATE_SYMLINK_FAILED (FASP_ERR_LOCAL_BASE - 15)
#define FASP_ERR_FILEPASS            (FASP_ERR_LOCAL_BASE - 16)

#define FASP_ERR_LOCAL_END           (FASP_ERR_LOCAL_BASE - 16)
#define FASP_ERR_LOCAL_NUM           (FASP_ERR_LOCAL_BASE - FASP_ERR_LOCAL_END)



#endif /* _FASP_DS_ERROR_H_ */

