// This is the complete, canonical list of all XML tags that the config file
// system is capable of understanding and navigating with.  If a tag is not
// in this list, any node with that tag is ignored (as are all of its
// descendants).

// No multiple inclusion security, please!
// This list no longer needs to be sorted.

hard_config_name( aaa )
hard_config_name( access )
hard_config_name( aggregate )
hard_config_name( allowed )
hard_config_name( bandwidth )
hard_config_name( cap )
hard_config_name( capacity )
hard_config_name( change_point )
hard_config_name( change_points )
hard_config_name( conf )
hard_config_name( CONF )
hard_config_name( default )
hard_config_name( defaults )
hard_config_name( epoch )
hard_config_name( fasp_ip_address )
hard_config_name( fasp_udp_port )
hard_config_name( file_io )
hard_config_name( file_system )
hard_config_name( flow )
hard_config_name( group )
hard_config_name( groups )
hard_config_name( http )
hard_config_name( id )
hard_config_name( in )
hard_config_name( log_stats_interval )
hard_config_name( maxflows )
hard_config_name( mcast_group_address )
hard_config_name( mcast_iface_address )
hard_config_name( mcast_port )
hard_config_name( min_queue )
hard_config_name( min_rate )
hard_config_name( name )
hard_config_name( operations )
hard_config_name( on )
hard_config_name( out )
hard_config_name( path )
hard_config_name( paths )
hard_config_name( policy )
hard_config_name( port )
hard_config_name( ports )
hard_config_name( priority )
hard_config_name( protocol_options )
hard_config_name( provider )
hard_config_name( qb_over_qmax )
hard_config_name( rate_instru_type )
hard_config_name( realm )
hard_config_name( realms )
hard_config_name( schedule )
hard_config_name( server )
hard_config_name( target_queue )
hard_config_name( target_rate )
hard_config_name( tightness_in )
hard_config_name( tightness_out )
hard_config_name( transfer )
hard_config_name( trunk )
hard_config_name( trunk_id )
hard_config_name( trunks )
hard_config_name( user )
hard_config_name( users )
hard_config_name( user_value )
hard_config_name( value )

hard_config_name( encryption )
hard_config_name( allowed_cipher )
hard_config_name( lock )
hard_config_name( content_protection_required )
hard_config_name( content_protection_strong_pass_required ) 

hard_config_name( http_server )
hard_config_name( cert_file )
hard_config_name( bind_address )
hard_config_name( key_file )
hard_config_name( mgmt_address )
hard_config_name( http_port )
hard_config_name( https_port )
hard_config_name( file_root )
hard_config_name( restartable_transfers )
hard_config_name( enable_http )
hard_config_name( enable_https )
hard_config_name( session_activity_timeout )

hard_config_name( absolute )
hard_config_name( show_as )
hard_config_name( description )
hard_config_name( filter )

hard_config_name( read_allowed )
hard_config_name( write_allowed )
hard_config_name( dir_allowed )

hard_config_name( file_create_mode )
hard_config_name( file_create_grant_mask )
hard_config_name( directory_create_mode )
hard_config_name( directory_create_grant_mask )

hard_config_name( read_block_size )
hard_config_name( write_block_size )
hard_config_name( use_file_cache )
hard_config_name( max_file_cache_buffer )
hard_config_name( ring_buf_units ) 
hard_config_name( resume_suffix )
hard_config_name( preserve_attributes )
hard_config_name( overwrite )
hard_config_name( file_manifest )
hard_config_name( file_manifest_path )
hard_config_name( pre_calculate_job_size )
hard_config_name( storage_rc )
hard_config_name( adaptive )
hard_config_name( buf_min ) 
hard_config_name( buf_target ) 
hard_config_name( buf_delta ) 

hard_config_name( bind_ip_address )
hard_config_name( bind_udp_port )
hard_config_name( disable_batching )
hard_config_name( sessini_optimization )
hard_config_name( max_sock_buffer )
hard_config_name( min_sock_buffer )

hard_config_name( authorization )
hard_config_name( external_provider )
hard_config_name( url )
hard_config_name( soap_action )
    
hard_config_name( token )
hard_config_name( encryption_key )
hard_config_name( encryption_type )
hard_config_name( life_seconds )

hard_config_name( variable )

hard_config_name( external_user_source )

hard_config_name( item )

hard_config_name( test_string_list )

hard_config_name( central_server )
hard_config_name( address )

hard_config_name( database )
hard_config_name( adapter )
hard_config_name( password )
hard_config_name( database_name )
hard_config_name( threads )
hard_config_name( exit_on_database_error )
hard_config_name( session_progress )
hard_config_name( session_progress_interval )
hard_config_name( file_events )
hard_config_name( file_progress )
hard_config_name( file_errors )
hard_config_name( file_progress_interval )
hard_config_name( files_per_session )
hard_config_name( ignore_empty_files )
hard_config_name( ignore_skipped_files )
hard_config_name( ignore_no_transfer_files )
hard_config_name( rate_events )

hard_config_name( http_session )
hard_config_name( operation )
hard_config_name( cookie )
hard_config_name( source )
hard_config_name( destination )
hard_config_name( createdir )
hard_config_name( mustbedir )
hard_config_name( resume )
hard_config_name( rate )
hard_config_name( limit )
hard_config_name( license )
hard_config_name( pretransfer )
hard_config_name( precalculate )

hard_config_name( reason )
hard_config_name( code )
hard_config_name( stats )
hard_config_name( files )
hard_config_name( bytes )

hard_config_name( excludes )
hard_config_name( exclude )

hard_config_name( precedence )

hard_config_name( reset_key )

hard_config_name( session )

// V1 stuff

hard_config_name( FASP )
hard_config_name( DirectoryCreateMode )
hard_config_name( FASP_AUTH )
hard_config_name( AuthorizationRequired )
hard_config_name( AuthorizationURL )
hard_config_name( CENTRAL )
hard_config_name( HttpPort )
hard_config_name( HttpAddress )
hard_config_name( DATABASE )
hard_config_name( Adapter )
hard_config_name( Server )
hard_config_name( Port )
hard_config_name( User )
hard_config_name( Password )
hard_config_name( DatabaseName )
hard_config_name( VLINK )
hard_config_name( ID )
hard_config_name( On )
hard_config_name( InboundAggregateCapKbps )
hard_config_name( OutboundAggregateCapKbps )
hard_config_name( WEB )
hard_config_name( SshPort )
hard_config_name( UdpPort )
hard_config_name( Policy )
hard_config_name( BandwidthCap )
hard_config_name( MinRate )
hard_config_name( LockPolicy )
hard_config_name( LockTargetRate )
hard_config_name( LockMinRate )
hard_config_name( PathMTU )
hard_config_name( DetectBW )
hard_config_name( TargetRate )
hard_config_name( Encryption )
hard_config_name( HttpFallback )
hard_config_name( HttpFallbackPort )
hard_config_name( HttpsFallbackPort )

#undef hard_config_name
